embedded_iframes/config/routes.rb
Rails.application.routes.draw do
  resources :stats, only: :index
  resources :embeddeds, only: [:show, :create, :edit]

  devise_for :users
  root to: 'welcome#index'
end

embedded_iframes/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

embedded_iframes/app/models/embedded.rb
class Embedded < ApplicationRecord
  belongs_to :user
  has_secure_token :token
end

embedded_iframes/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :embeddeds, dependent: :destroy
end

embedded_iframes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

embedded_iframes/app/controllers/embeddeds_controller.rb
class EmbeddedsController < ApplicationController
  def show
    headers["X-Frame-Options"] = "allowall"
    @embedded = Embedded.find_by(token: params[:id])
    render template: "#{@embedded.controller}/#{@embedded.action}", layout: false
  end

  def create
    @embedded = current_user.embeddeds.create(embedded_params)
    redirect_to [:edit, @embedded]
  end

  def edit
    @embedded = current_user.embeddeds.find(params[:id])
  end

  private

  def embedded_params
    params.require(:embedded).permit(:controller, :action)
  end
end

embedded_iframes/app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
    @rand = rand()
  end
end

embedded_iframes/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

embedded_iframes/app/helpers/application_helper.rb
module ApplicationHelper
end

embedded_iframes/app/helpers/welcome_helper.rb
module WelcomeHelper
end

embedded_iframes/app/views/embeddeds/edit.html.erb
<%= turbo_frame_tag :embedded do %>
  <% embedded_iframe = content_tag(
    :iframe,
    nil,
    width: "100%",
    height: "400px",
    src: embedded_url(id: @embedded.token)
  ) %>
  <%= text_area_tag :embedded, embedded_iframe, class: "form-control" %>
<% end %>

embedded_iframes/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light py-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" data-config-id="brand">
      <%= image_tag 'logo.png', class: 'img-fluid' %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav">
      <ul class="d-none d-lg-flex navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0 d-lg-none">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

embedded_iframes/app/views/layouts/_navigation_links.html.erb
<li class="nav-item me-4">
  <%= link_to "Home", root_path, class: 'nav-link' %>
</li>
<% if user_signed_in? %>
  <li class="nav-item me-4">
    <%= link_to "My Account", edit_user_registration_path, class: "nav-link" %>
  </li>
  <li class="nav-item me-4">
    <%= link_to "Sign Out", destroy_user_session_path, "data-turbo-method": :delete, class: "nav-link" %>
  </li>
<% else %>
  <li class="nav-item me-4">
    <%= link_to "Sign In", new_user_session_path, class: 'nav-link' %>
  </li>
<% end %>

embedded_iframes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drifting Ruby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class='bg-light'>
    <div class="container bg-white border pb-3">
      <%= render 'layouts/navigation' %>
      <% flash.each do |type, msg| %>
        <% if type == 'alert' %>
          <%= content_tag :div, msg, class: "alert alert-danger", role: :alert %>
          <% else %>
          <%= content_tag :div, msg, class: "alert alert-primary", role: :alert %>
        <% end %>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

embedded_iframes/app/views/stats/index.html.erb
<%= turbo_frame_tag :stats do %>
  <h1>Some Stats</h1>
  <%= rand() %>
<% end %>

embedded_iframes/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<div>
  <%= turbo_frame_tag :embedded do %>
    <%= button_to "Create Embedded Link", embeddeds_path(
      params: {
        embedded: {
          controller: :stats,
          action: :index
        }
      }
    ) %>
  <% end %>
  <%= turbo_frame_tag :stats, src: stats_url %>
</div>